import os

CHECKOUT_VERSION = os.getenv("CHECKOUT_VERSION", "v6")
SETUP_NODE_VERSION = os.getenv("SETUP_NODE_VERSION", "v6")
SETUP_PYTHON_VERSION = os.getenv("SETUP_PYTHON_VERSION", "v5")
SETUP_JQ_VERSION = os.getenv("SETUP_JQ_VERSION", "v3.0.1")
SETUP_YQ_VERSION = os.getenv("SETUP_YQ_VERSION", "latest")

SETUP_BUILDX_VERSION = os.getenv("SETUP_BUILDX_VERSION", "v3")
CACHE_ACTIONS_VERSION = os.getenv("CACHE_ACTIONS_VERSION", "v4")
DOCKER_BUILD_AND_PUSH_VERSION = os.getenv("DOCKER_BUILD_AND_PUSH_VERSION", "v6")

SETUP_MAVEN_VERSION = os.getenv("SETUP_MAVEN_VERSION", "v1.18.0")
SETUP_JFROG_VERSION = os.getenv("SETUP_JFROG_VERSION", "v4")

SETUP_KUBECTL_VERSION = os.getenv("SETUP_KUBECTL_VERSION", "v3")
SETUP_HELM_VERSION = os.getenv("SETUP_HELM_VERSION", "v3")
SETUP_KUBELOGIN_VERSION = os.getenv("SETUP_KUBELOGIN_VERSION", "v1")
SETUP_TERRAFORM_VERSION = os.getenv("SETUP_TERRAFORM_VERSION", "v3")
